config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 10 }
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :check_if_admin, only: %i[new create]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def check_if_admin
    redirect_to(new_user_session_path, alert: 'Faça login antes de acessar essa página.') unless current_user&.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/index.html.erb
<div id="index__wrapper">
  <div id="index__content">
    <ul id="index__list_of_articles">
      <% @articles.reverse_each do |article| %>
        <div>
            <span><li><%= link_to article.title, article %></li><%= I18n.l(article.created_at, format: :short_datetime) %></span>
        </div>
      <% end %>
    </ul>
  </div>
</div>

app/views/articles/new.html.erb
<div id="new__wrapper">
  <div id="new__content">
    <%= form_with model: @article, local: true do |form| %>
      <div id="new__header">
        <h1>Nova publicação</h1>
        <div id="show__divider"></div>
      </div>

      <div id="new__form_title">
        <%= form.label :title, "Título" %>
        <%= form.text_field :title %>
      </div>

      <div id="new__form_content">
        <%= form.hidden_field :content, id: "article_content" %>
        <%= form.rich_text_area :content, class: "trix-content" %>
      </div>

      <div id="new__form_button">
        <%= form.submit "Create Article" %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div id="show__wrapper">
  <div id="show__content">
    <div id="show__header">
      <h1><%= @article.title %></h1>
      <%= I18n.l(@article.created_at, format: :full_datetime) %>
    </div>
    <div id="show__divider"></div>
    <div class="trix-content"><%= @article.content.to_s.html_safe %></div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>motoka.dev | blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@200..800&display=swap" rel="stylesheet">
  </head>

  <body>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p> 
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div id="header__wrapper">
  <h1 id="header__title"><%= link_to "motoka.dev", articles_path %></h1>
</div>